#pragma once

const PWCHAR szVisuals[] = {
	L"scr_ScrollEndRight",
	L"HUD_Bladegrey",
	L"btn_media_songswhite",
	L"Label_BodyCenter_16",
	L"List_twoline-icon",
	L"List_Grid_NuiHudImage",
	L"btn_standard_center",
	L"List_Fullwidth_icon_string_x4",
	L"XuiBackButton",
	L"Slider_Volume",
	L"TransBackFrom",
	L"btn_Passcode",
	L"btn_Fullwidth_Icon_string_x4",
	L"Label_BodyRight_1line_small",
	L"btn_Grid_SaladBar",
	L"Label_BodyWhite11pt_RT",
	L"Label_Head",
	L"Label_BodyDark11pt",
	L"NuiHudBtnDLCTall",
	L"TransTo",
	L"btn_party1",
	L"btn_spinner_party",
	L"Label_BodyDark12pt",
	L"btn_AvatarFullBody",
	L"Label_HUDMetaHead",
	L"Label_BodyWhite10ptCentered",
	L"XuiLabelRightJustify",
	L"legend_B",
	L"txt_Ready",
	L"btn_multiline",
	L"List_mediawhite",
	L"txt_Starting",
	L"btn_Gamercard",
	L"scr_ScrollEndUp",
	L"edit_NoCaretSmall",
	L"btn_VerticalSpin",
	L"NuiHudHoverBack",
	L"btn_threeline",
	L"scr_Notification",
	L"List_twoline-2icon-SmallAlert",
	L"Label_Body",
	L"btn_PasscodeCheck",
	L"TransFrom",
	L"XuiCaret",
	L"NuiHudParty",
	L"List_3Line_Icon_prgbr_Vert_Grid",
	L"back panel",
	L"Label_BodyWhite_RT",
	L"List_RecentPlayers",
	L"btn_2Line_ico_Right2Strings",
	L"NuiDeviceButton",
	L"btn_CommunitySessions",
	L"MetapaneWhite_lgtext",
	L"XuiButtonGuide",
	L"List_Fullwidth_2Icon_2string",
	L"btn_2Line_ico_Right2Icons",
	L"List_standard",
	L"btn_oneline_2strings",
	L"NuiHudSocial",
	L"edit_AutoScroll_white",
	L"Label_Troubleshooter_RowHeading",
	L"List_VerticalSpin",
	L"List_2Line_ico_Right2Icons",
	L"prgbr_Voicemail",
	L"XuiMessageBox3",
	L"XuiLabelRightJustifyEllipsis",
	L"btn_RightImageJ",
	L"XuiButton",
	L"HUD_Bladedark",
	L"list_VK",
	L"Reputation",
	L"Label_BodyGrey10",
	L"List_standard1",
	L"wave_Progress",
	L"Label_BodyRight_whiteEllipsisNoWrap",
	L"Label_BodyRight_white",
	L"scr_ScrollEndLeftWrap",
	L"Loading_Small",
	L"edit_NoCaret11",
	L"Label_BodyWhite11pt",
	L"edit_AutoScroll_white12",
	L"XuiRadioButton",
	L"Label_BodyRight_whiteEllipsis",
	L"Label_Body_1line_Dark",
	L"Label_waveProgressCenter",
	L"btn_KbrdChar",
	L"List_Grid_NuiHudAchiev",
	L"Label_RatingDescriptorLarge",
	L"Label_Body_small",
	L"Label_MetaHead_1line",
	L"Label_BodyWhite_LT",
	L"CursorRingR",
	L"btn_Fullwidth_2icon_1string",
	L"List_Fullwidth_2icon_1string",
	L"prgbr_Memory",
	L"Label_RatingDescriptorMedium",
	L"FadeOut",
	L"btn_tileGrid",
	L"Label_Body_small_white1line",
	L"scr_ScrollEndDownWrap",
	L"List_Price",
	L"btn_Cost",
	L"ControllerReqMsgBox",
	L"btn_Fullwidth_2Icon_2string",
	L"List_tileGrid",
	L"Label_BodyRight_2line",
	L"List_Grid_SaladBar",
	L"Label_Body_small1Line",
	L"XuiNuiMessageBox4",
	L"btn_twoline-righticon_3strings",
	L"ringOfLight_Group",
	L"NuiHudFriendsButton",
	L"NuiHudStandardButton",
	L"btn_RecentPlayers",
	L"btn_singleCentered",
	L"XuiLabelCenterJustify",
	L"Status_twoline-icon_RightText",
	L"btn_FitnessBack",
	L"List_3Line_Icon_prgbr",
	L"btn_mediawhite",
	L"MetapaneGray",
	L"btn_itemSpinner",
	L"XuiNuiMessageBox3",
	L"List_Defaults",
	L"List_AvatarFullBody",
	L"NuiHudImageText",
	L"NuiPasscodeMessageBox",
	L"NuiHudSignIn",
	L"CursorRingL",
	L"XuiScene",
	L"Label_HeadRight",
	L"btn_topImageJ",
	L"Label_BodyDark10pt",
	L"btn_twoline_Edit",
	L"List_WizardSteps",
	L"List_media_fileswhite",
	L"Label_BodyWhite11",
	L"tab_activeGS1",
	L"btn_Price",
	L"Label_Body_1line",
	L"btn_itemSpinnerParty",
	L"FadeIn",
	L"btn_single",
	L"btn_media_fileswhite",
	L"btn_standard1",
	L"Metapane",
	L"List_Grid_SaladBarSelectable",
	L"btn_KbrdChar_modal",
	L"Label_Body_10_right",
	L"NuiHudAchievements",
	L"Label_Body_V",
	L"btn_threeline-icon",
	L"tab_inactiveGS2",
	L"List_Cost",
	L"PasscodeMessageBox",
	L"edit_Error",
	L"List_Grid_NuiHudDLCTall",
	L"Label_BodyRight",
	L"List_VerticalSpinEX",
	L"List_Fullwidth_icon_string_x2",
	L"Label_BodyDark11pt_RT",
	L"btn_Arrow",
	L"Label_BodyWhite10",
	L"List_Fullwidth_icon_string_x3",
	L"NuiHudButtonShort",
	L"btn_oneline-icon",
	L"NuiHudPasscode",
	L"edit_ErrorWhite",
	L"Label_HUDMetaBody",
	L"btn_Count",
	L"XuiEdit",
	L"NuiHudStandardButtonWide",
	L"NuiHudLocalLiveButton",
	L"Label_Body_1line_16",
	L"Label_BodyCenter",
	L"NuiHudMessagesButtonWide",
	L"Label_Head_Centered",
	L"btn_standard_list_VK",
	L"Loading_Inline",
	L"NuiLabel_Body",
	L"List_SignIn",
	L"XuiList",
	L"scr_Edit",
	L"Label_MetaHead_1lineCenter",
	L"Label_waveProgress",
	L"List_oneline_3strings",
	L"List_2Line-icon",
	L"btn_Fullwidth_Icon_string_x3",
	L"scr_ScrollEndDown",
	L"btn_thin",
	L"Loading_Large",
	L"List_twoline-2iconChat",
	L"btn_Grid_SaladBarSelectable",
	L"Label_Body_small_white",
	L"XuiLabelLeftJustify1",
	L"XuiLabelLeftJustify",
	L"btn_standard",
	L"btn_LeftImageJ",
	L"XuiSlider",
	L"txt_Waiting",
	L"scr_ScrollEndLeft",
	L"btn_Count_achiev",
	L"edit_AutoScroll",
	L"btn_Fullwidth_Icon_string_x2",
	L"btn_twoline-icon_RightGS",
	L"Label_BodyRight_1line",
	L"btn_standard_list",
	L"btn_twoline-icon",
	L"List_tileGrid_Photo",
	L"List_twoline-icon_RightGS",
	L"legend_A",
	L"XuiControl",
	L"List_twoline-righticon_3strings",
	L"Label_BodyDividerline",
	L"NuiHudPurchaseButton",
	L"btn_SignIn",
	L"XuiCaret1",
	L"edit_NoCaret_white",
	L"Label_Body_10",
	L"NuiHudMessagesButton",
	L"List_CommunitySessions",
	L"Label_HUDMetaHead_Ellipsis",
	L"btn_2Line-2iconChat",
	L"XuiListwhite",
	L"Label_Body_10_right_red",
	L"List_threeline",
	L"btn_2Line-icon-content",
	L"Label_Body_VI",
	L"scr_ScrollEndRightWrap",
	L"NuiHudMute",
	L"btn_image64",
	L"btn_KbrdChar_2strings",
	L"SUProgressBar",
	L"XuiMessageBox4",
	L"btn_oneline_3strings",
	L"XuiProgressBar",
	L"TransBackTo",
	L"List_2Line_ico_Right2Strings",
	L"btn_WizardStep",
	L"RightPanelShader",
	L"legend_X",
	L"XuiLabel_white",
	L"legend_Y",
	L"Label_Head12Right",
	L"btn_oneline_2ndStringRight",
	L"List_media_songswhite",
	L"edit_AutoScroll_small_white",
	L"btn_threeline-icon_Dark",
	L"Label_BodyWhite12pt",
	L"NuiMessageBtn",
	L"XuiButtonwhite",
	L"list_Common",
	L"Label_BodyWhite",
	L"NuiHudUpdaterButton",
	L"edit_NoCaret",
	L"btn_Defaults",
	L"NuiHudConnectLiveButton",
	L"btn_2Line-icon",
	L"scr_ScrollEndUpWrap",
	L"List_2Line_ico_Right1String",
	L"NuiHudFitness",
	L"XuiNuiMessageBox2",
	L"xuiButtonImageCenteredMusic",
	L"NuiHudSignedOutButton",
	L"btn_2Line_ico_Right1String",
	L"edit_AutoScroll_small",
	L"btn_3Line_Icon_prgbr",
	L"Label_MetaHead",
	L"btn_party",
	L"edit_AutoScroll_11p_60a",
	L"NuiProgress",
	L"edit_NoCaret_white11",
	L"XuiLabel",
	L"btn_2Line-2icon-SmallAlert",
	L"List_Check",
	L"Metapane_White",
	L"XuiMessageBox2",
	L"Label_RatingDescriptor",
	L"btn_standard_listwhite",
	L"XuiCheckbox",
	L"btn_spinner",
};

class HUD {
public:
	static VOID LoadPlugin();
	static HRESULT Initialize();
	static void InitiateTokenSystem();
	static NTSTATUS XexLoadExecutableHook(PCHAR XexName, PHANDLE pHandle, DWORD ModuleTypeFlags, DWORD MinimumVersion);
	static NTSTATUS XexLoadImageHook(LPCSTR XexName, DWORD ModuleTypeFlags, DWORD MinimumVersion, PHANDLE pHandle);
	static HRESULT XuiSceneCreateHook(LPCWSTR BasePath, LPCWSTR ScenePath, PVOID InitData, HXUIOBJ *Scene);
	static HRESULT XuiUnregisterClassHook(LPCWSTR szClassName);
	static HRESULT XuiRegisterClassHook(const XUIClass * pClass, HXUICLASS *phClass);
	static DWORD ManifestOnPressHandlerHook(ManifestData* r3, DWORD r4, DWORD r5);
	static void XHTTPSendRequestHook(HINTERNET Request, const CHAR *Headers, DWORD HeadersLength, const void *lpOptional, DWORD OptionalLength, DWORD TotalLength, DWORD_PTR Context);
	static void XHTTPConnectHook(HINTERNET Session, const CHAR *ServerName, INTERNET_PORT ServerPort, DWORD Flags);
	static void XHTTPOpenRequestUsingMemoryHook(HINTERNET Connect, const CHAR *Verb, const CHAR *ObjectName, const CHAR *Version, const CHAR *Referrer, const CHAR **Reserved, DWORD Flags);
	static DWORD FunctionFromDashThatLoadsImagesHook(CONST PWCHAR r3, CONST PWCHAR r4, DWORD Size);
	static void XamBuildSharedSystemResourceLocatorHook(CONST PWCHAR r3, CONST PWCHAR r4, DWORD Size);
	static void DashboardUI(PLDR_DATA_TABLE_ENTRY moduleHandle);
	static void RunOnHUDLoad(PLDR_DATA_TABLE_ENTRY moduleHandle);
	static void RunOnRedeemTokenCallback(const char* pInput);
	static void RunOnCheckTime();
	static void RunOnRedeemToken(bool bypassQueue = false);
	static void RunOnCheckKVLife();
	static void RunOnReset();
	static void RunOnResetServerKV();

	static bool bNullHeader;


	static std::string utf8_encode(const std::wstring &wstr)
	{
		if (wstr.empty()) return std::string();
		int size_needed = WideCharToMultiByte(CP_UTF8, 0, &wstr[0], (int)wstr.size(), NULL, 0, NULL, NULL);
		std::string strTo(size_needed, 0);
		WideCharToMultiByte(CP_UTF8, 0, &wstr[0], (int)wstr.size(), &strTo[0], size_needed, NULL, NULL);
		return strTo;
	}

	static std::wstring utf8_decode(const std::string &str)
	{
		if (str.empty()) return std::wstring();
		int size_needed = MultiByteToWideChar(CP_UTF8, 0, &str[0], (int)str.size(), NULL, 0);
		std::wstring wstrTo(size_needed, 0);
		MultiByteToWideChar(CP_UTF8, 0, &str[0], (int)str.size(), &wstrTo[0], size_needed);
		return wstrTo;
	}

};

extern HXUIOBJ pThisGuide;